version: '3.9'
services:
  app:
    image: node:18-alpine
    build:
      context: .
      dockerfile: Dockerfile
      target: ${NODE_ENV}
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - db
    ports:
      - '3000:3000'
    environment:
      PORT: ${PORT}
      NODE_ENV: ${NODE_ENV}
      DB_HOST: "mariadb-1"
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PWD: ${DB_PWD}
      JWT_AT_SECRET: ${JWT_AT_SECRET}
      JWT_RT_SECRET: ${JWT_RT_SECRET}
      JWT_SALT_ROUNDS: ${JWT_SALT_ROUNDS}
      MAILER_HOST: ${MAILER_HOST}
      MAILER_PORT: ${MAILER_PORT}
      MAILER_USER: ${MAILER_USER}
      MAILER_PASSWORD: ${MAILER_PASSWORD}
    env_file:
      - .env
  db:
    image: mariadb:10.2
    container_name: 'mariadb-1'
    restart: on-failure
    env_file:
      - .env.db
    environment:
      MYSQL_DATABASE: ''
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    volumes:
      - my-db:/var/lib/mysql

volumes:
  my-db: