#!/bin/bash

usage() {
  echo "Usage: $0 [ -n NAME ]"
}

exit_abnormal() {
  usage
  exit 1
}

while getopts n: flag
do
    case "${flag}" in
        n) lib_name=${OPTARG};;
        :)  echo "Error: -${OPTARG} requires an argument."
            exit_abnormal
            ;;
        *) exit_abnormal

    esac
done

cd ../libs || exit ; mkdir "$lib_name" ; cd "$lib_name" || exit;

mkdir "src" ; cd "src" || exit; touch "$lib_name.module.ts" && touch "$lib_name.service.ts"
cd ..
touch ".gitignore"
echo "# compiled output
/dist
/node_modules

# Logs
logs
*.log
npm-debug.log*
pnpm-debug.log*
yarn-debug.log*
yarn-error.log*
lerna-debug.log*

# OS
.DS_Store

# Tests
/coverage
/.nyc_output

# IDEs and editors
/.idea
.project
.classpath
.c9/
*.launch
.settings/
*.sublime-workspace

# IDE - VSCode
.vscode/*
!.vscode/settings.json
!.vscode/tasks.json
!.vscode/launch.json
!.vscode/extensions.json" > ".gitignore"

touch ".eslintrc.js"
echo "module.exports = {
  parser: '@typescript-eslint/parser',
  parserOptions: {
  project: 'tsconfig.json',
  sourceType: 'module',
  },
  plugins: ['@typescript-eslint/eslint-plugin'],
  extends: [
    'plugin:@typescript-eslint/recommended',
  ],
  root: true,
  env: {
    node: true,
    jest: true,
  },
  ignorePatterns: ['.eslintrc.js'],
  rules: {
    '@typescript-eslint/interface-name-prefix': 'off',
    '@typescript-eslint/explicit-function-return-type': 'off',
    '@typescript-eslint/explicit-module-boundary-types': 'off',
    '@typescript-eslint/no-explicit-any': 'off',
  },
};" > ".eslintrc.js"

touch "index.js"
echo "export * from \"./src/$lib_name.module.ts\"" > "index.js"

touch "jest.config.json"
echo "{
  \"moduleFileExtensions\": [\"js\", \"json\", \"ts\"],
  \"rootDir\": \".\",
  \"testEnvironment\": \"node\",
  \"testRegex\": \".spec(-integration)?.ts$\",
  \"transform\": {
  \"^.+\\\.ts$\": \"ts-jest\"
  }
}" > "jest.config.json"

touch "package.json"
echo "{
  \"name\": \"@app/$lib_name\",
  \"version\": \"0.0.1\",
  \"main\": \"dist/index.js\",
  \"license\": \"UNLICENSED\",
  \"private\": true,
  \"scripts\": {
    \"build\": \"tsc\",
    \"build:watch\": \"tsc --watch\",
    \"test\": \"jest\",
    \"test:watch\": \"jest --watch\",
    \"test:cov\": \"jest --coverage\"
  },
  \"dependencies\": {
    \"@nestjs/common\": \"^8.0.0\",
    \"@nestjs/config\": \"^2.2.0\",
    \"@nestjs/core\": \"^8.0.0\",
    \"@nestjs/platform-express\": \"^8.0.0\",
    \"@nestjs/typeorm\": \"^9.0.1\",
    \"@types/jest\": \"^29.2.2\",
    \"@types/js-yaml\": \"^4.0.5\",
    \"class-transformer\": \"^0.5.1\",
    \"class-validator\": \"^0.13.2\",
    \"jest\": \"^29.3.1\",
    \"js-yaml\": \"^4.1.0\",
    \"reflect-metadata\": \"^0.1.12\",
    \"rimraf\": \"^3.0.2\",
    \"rxjs\": \"^7.2.0\",
    \"ts-jest\": \"^29.0.3\",
    \"typeorm\": \"^0.3.10\"
  },
  \"devDependencies\": {
    \"@nestjs/cli\": \"^7.6.0\",
    \"@nestjs/schematics\": \"^7.3.0\",
    \"@nestjs/testing\": \"^7.6.15\",
    \"@types/express\": \"^4.17.11\",
    \"@types/node\": \"^14.14.36\",
    \"@types/supertest\": \"^2.0.10\",
    \"@typescript-eslint/eslint-plugin\": \"^4.19.0\",
    \"@typescript-eslint/parser\": \"^4.19.0\",
    \"eslint\": \"^7.22.0\",
    \"eslint-config-prettier\": \"^8.1.0\",
    \"eslint-plugin-prettier\": \"^3.3.1\",
    \"prettier\": \"^2.2.1\",
    \"supertest\": \"^6.1.3\",
    \"ts-loader\": \"^8.0.18\",
    \"ts-node\": \"^9.1.1\",
    \"tsconfig-paths\": \"^3.9.0\",
    \"typescript\": \"^4.2.3\"
  }
}" > "package.json"

touch tsconfig.json
echo "{
  \"compilerOptions\": {
    \"module\": \"commonjs\",
    \"declaration\": true,
    \"removeComments\": true,
    \"emitDecoratorMetadata\": true,
    \"experimentalDecorators\": true,
    \"allowSyntheticDefaultImports\": true,
    \"target\": \"es2017\",
    \"sourceMap\": true,
    \"outDir\": \"dist\",
    \"baseUrl\": \"./\",
    \"incremental\": true
  },
  \"exclude\": [
    \"dist\",
    \"node_modules\",
    \"types\"
  ]
}" > "tsconfig.json"

yarn install

